---
- name: Play testador de conexão
  hosts: all
  gather_facts: True
  become: True
  remote_user: ansible
  vars_files:
    - senha.txt
  vars:
    ansible_password: "{{ senha }}"
  tasks:
    - name: Exibe nome e SO de todas as máquinas do parque
      ansible.builtin.debug:
        msg: "Nome: {{ ansible_nodename }}; IP: {{ ansible_default_ipv4.address }}"
...
