---
- name: Play testador de conexão (ambiente de desenvolvimento)
  hosts: dev
  gather_facts: True
  become: True
  remote_user: ansibledev
  vars_files:
    - senha.txt
  vars:
    ansible_password: "{{ senhadev }}"
  tasks:
    - name: Exibe nome e SO das máquinas de desenvolvimento
      ansible.builtin.debug:
        msg: "Nome: {{ ansible_nodename }}; IP: {{ ansible_default_ipv4.address }}"

- name: Play testador de conexão (ambiente de produção)
  hosts: prod
  gather_facts: True
  become: True
  remote_user: ansibleprod
  vars_files:
    - senha.txt
  vars:
    ansible_password: "{{ senhaprod }}"
  tasks:
    - name: Exibe nome e SO das máquinas de produção
      ansible.builtin.debug:
        msg: "Nome: {{ ansible_nodename }}; IP: {{ ansible_default_ipv4.address }}"
...
