---
- name: Play testador de conexão (ambiente de desenvolvimento)
  hosts: dev
  gather_facts: True
  become: True
  remote_user: ansibledev
  vars_files:
    - senha.txt
  vars:
    ansible_ssh_private_key_file: "~ansibledev/.ssh/id_rsa"
    ansible_become_password: "{{ senhadev }}"
  tasks:
    - name: Exibe nome e SO das máquinas de desenvolvimento
      ansible.builtin.debug:
        msg: "Nome: {{ ansible_nodename }}; IP: {{ ansible_default_ipv4.address }}"
...
